import initTabNav from './modules/tabnav.js';
import initAccordion from './modules/accordion.js';
import initAnimacaoScroll from './modules/scroll-animacao.js';
import initScrollSuave from './modules/scroll-suave.js';
import initModal from './modules/modal.js';
import initToolTip from './modules/tooltip.js';
import initDropDownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initFechAnimais from './modules/fetch-animais.js';
import initFetchBitcoin from './modules/fetch-bitcoin.js';

initTabNav();
initAccordion();
initAnimacaoScroll();
initScrollSuave();
initModal();
initToolTip();
initDropDownMenu();
initMenuMobile();
initFuncionamento();
initFechAnimais();
initFetchBitcoin();
